### ISSUE TITLE
Meaning and use of the "seed" field for ML-KEM 768?

### ISSUE THREAD

**Issue by rod-chapman** [post-quantum-cryptography/KAT#1]
Many thanks for adding these KATs.

Could someone explain the meaning and use of the "seed" field please?
For the ML-KEM 768 KATs, I see that the "seed" field is 48 bytes.

On the other hand, looking at FIPS 203, I see that I need 32 bytes of random input z in Algorithm 15 (ML-KEM.KeyGen), plus another 32 bytes of random input for the value d in Algorithm 12 (K-PKE.KeyGen).

Am I supposed to use "seed" to derive those 2 32-byte inputs? If so, how?

**Comment by rod-chapman** [comment]
I've been digging a bit. It seems that the seed is used to initialize some sort of DBRG that is used to generate the inputs for each KAT. To reproduce that, it seems I need to build the entire Kyber distribution and OpenSSL, which is something of a pain.

Could you possibly just include the 32-byte d and z values in the KAT file(s) please following the seed? That would be a huge help.

**Comment by rod-chapman** [comment]
Actually - I think it's _three_ random 32-byte values... the D and Z values that are required by MLKEM_KeyGen(), and the M value requires by MLKEM_Encaps(). Is that right?

**Comment by rod-chapman** [comment]
I have tried to reproduce the DRBG behaviour by re-compiling the rng.[hc] files from the Kyber/ref directory, and linking with libcrypto.a from OpenSSL, with no luck. Either I'm generating the D, Z and M values wrong from the Seed, or they're right, and my MLKEM code is wrong somewhere... Could you possibly let me know the D, Z, and M values for the _first_ (i.e. count = 0) KAT in the file for MLKEM-768 please?

**Comment by rod-chapman** [comment]
More data: For the first (count = 0) KAT, having fixed the XOF() parameter order issue, my pk value matches yours, so my D input must be correct. sk also looks correct, but not the final 32 bytes, which is just a copy of the Z random input, so my Z does not match yours. I can't see why that is...

**Comment by kriskwiatkowski** [comment]
Indeed seed is to initialize ``AES-CRT-DRBG``.
I've updated KATs with ``z``, ``d`` and ``m`` (aka ``msg``).

**Comment by rod-chapman** [comment]
That’s great – many thanks. I am on trip to London today, but should be able to take a look on the train…

  *   Rod


On 12/10/2023, 00:46, "Kris" ***@***.******@***.***>> wrote:

Indeed seed is to initialize AES-CRT-DRBG.
I've updated KATs with z, d and m (aka msg).



Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by rod-chapman** [comment]
I can now reproduce the results of the first KAT perfectly, using the "(j,i)" ordering on the XOF calls.
I just need to now how you're modifying seed for the subsequent KATs and we should be there.

**Comment by rod-chapman** [comment]
I see that “seed” is changing for each KAT now. For the first seed, I get identical Z, D, and Msg now.

But… how are you deriving the second and subsequent seeds?

  *   Rod






Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by rod-chapman** [comment]
Actually... I don't need to know... I could just read the D, Z, and Msg fields from the RSP file and ignore the seed and the need to call the RNG altogether... that will make my build a lot simpler since I won't need to depend on the Kyber code and libcrypto.a - much better!

**Comment by kriskwiatkowski** [comment]
That 'seed' is a random value. So you need to initialise DRBG with that seed before calling keygen-encaps-decaps sequence (for each KAT)
Would you prefer something different?

I think if first KAT generates same z,d,m values then I think there should be no problem with others.

**Comment by kriskwiatkowski** [comment]
@rod-chapman If you use "(i,j)" ordering on the XOF calls, does the test fail?

**Comment by rod-chapman** [comment]
Yes - if I switch back to the "(i,j)" ordering, then it fails as expected.

Shall we both switch to "(i,j)" now and get it over with?

**Comment by kriskwiatkowski** [comment]
Thanks!

I'll switch to ``(i,j)`` and regenerate the vectors (later today, I'll let you know once done).

**Comment by kriskwiatkowski** [comment]
@rod-chapman Done. I've pushed new vectors. Can you check them?

**Comment by rod-chapman** [comment]
OK... still not getting it right somewhere.  See attached files. "ref.txt" is from your latest KAT file, but spaced out a bit so it's easier to look at.  "new.txt" is from my code with _both_ instances of XOF (in KeyGen and Encrypt) reverted to have the "i,j" parameter ordering as in the spec.  As you can see, _some_ of it matches, and some doesn't...
[ref.txt](https://github.com/post-quantum-cryptography/KAT/files/12893269/ref.txt)

[new.txt](https://github.com/post-quantum-cryptography/KAT/files/12893279/new.txt)

**Comment by rod-chapman** [comment]
For what it's worth, here's a more detailed output from my running the first KAT, showing the values of intermediate variables in K_PKE_KeyGen().
[new_detail.txt](https://github.com/post-quantum-cryptography/KAT/files/12897575/new_detail.txt)

**Comment by kriskwiatkowski** [comment]
cool. that will be useful. let me see

**Comment by kriskwiatkowski** [comment]
Interesting, seems we generate ``A_hat`` same way, at least in key generation. 

Mine:
```
seed = 259DED9468B043197319D7BBF61EAF6486120DB0BD02679AD99BAC4E1A7BAAA1
A[0,0] = 0267 002e 0195 0361 0910 0cc6 0278 08d7 0c05 046c 07a3 0015 033b 018b 0881 0257 01c5 00e0 072b 01f6 0a16 00f9 0229 05cd 0cf1 0824 007d 0892 085e 0069 083d 096f 06c7 05b1 000f 0a3f 0cdd 018c 0b41 07ec 0267 0bf5 07ff 04b0 0a77 0504 03d7 037d 054b 012b 0a41 02bd 0419 01e7 0709 0288 0554 05d7 04b9 029c 07f0 0950 0cc2 050c 077f 081e 09da 0c11 02e3 04dd 0b20 0ca9 0820 0a4e 0576 04a3 0573 018c 0633 0166 06bb 0873 0209 045b 0828 0b13 03df 07fa 0bbb 04a5 0ca3 0b11 0aa0 03e0 022c 0a7c 013d 0b41 0b66 0686 0556 071e 0420 0543 00f6 01cb 0b96 0343 006a 03a8 0299 0845 016e 0281 0a55 0a37 041d 0cd0 0cd4 0425 0be0 0489 0395 0a03 07d1 0252 0a13 00c3 00fe 0963 02cc 028b 04cf 0241 013a 0350 0a7f 027a 0021 0633 0aea 0030 09d2 0760 0043 0342 06b5 0445 0871 01cc 049b 0278 09a1 0a46 09ee 0aaf 01f8 025b 074c 0288 06ef 04db 087a 0436 0648 0867 04c2 0a85 007c 0965 0a5b 0a7d 0b0b 0538 0c33 0114 042f 079d 0317 08a9 0cd8 00ef 0c16 03c1 085f 0145 08cd 0a7b 0c60 00d7 0275 0c54 0681 050b 019c 070e 00d0 0b6a 09ba 0549 0a4e 021d 0028 0122 0239 0241 0cb9 006c 0ba7 0cd4 097b 0bb5 0596 0bf7 04fe 03be 02fb 0295 0b00 0237 0604 0ac5 0bf2 0b84 06b3 0b5c 038e 0ad1 0b38 0a15 0a5a 0b93 0b7b 0a56 0a00 01b3 039c 08e0 0aec 062b 0cb1 029c 0887 0123 0974 0671 0b17 04da 0b7a 02e9 05aa 093a 0bd5 0773 09d7 0555 
A[0,1] = 05bb 006e 0956 0872 0823 09ad 04e7 07c3 04a1 009a 0cb8 01c1 081b 0b1a 02b0 03b2 035c 0942 0bda 05d0 04cf 0561 0cdf 0531 0430 0820 03fc 02f8 086a 0a0f 0cfb 01de 01e9 00d0 04da 0bd1 0261 097f 08b2 08a3 03c7 028b 00fb 0b0e 0832 0975 072a 06f2 02d1 09b7 00cd 0237 0a4a 074f 0728 02ca 00f8 068e 0600 0b45 008d 03dd 07a5 058a 09d7 0846 0a3b 009a 084e 0131 0450 013d 00db 0602 0cd9 02e8 04d5 0242 00cd 0989 023f 0125 0171 0128 0990 04e1 0182 030d 04ae 09b3 06aa 045b 0abe 019b 09cf 00eb 0876 09d6 0031 021a 022f 0619 0932 0746 0744 0cf7 06b4 0107 0408 0886 05a8 0bcb 0583 017d 0cfb 027f 0bc2 0350 06df 0865 09b2 01de 09a7 0b13 0086 0a5f 0688 0c21 005a 0ba7 085b 0aa8 0692 0cc8 0528 0969 0ab6 04c4 05ff 00c9 0a4e 08d0 031f 0079 0783 054c 02b3 051c 0c3d 0ae0 04a3 0699 04d8 0173 0789 06db 0a3d 03df 05a5 0112 096a 0002 0184 0c9c 0afc 0c55 0c27 0ca9 0551 061c 08e8 07d5 0b7c 0859 00e6 09b4 0317 066a 0be7 0ab5 012b 0976 0cd3 0b3c 0bfa 0b6b 0c15 0cdb 0610 0420 08d3 0660 07e1 0729 0321 07c8 02d6 0a96 0259 012d 0892 04aa 0963 038c 043c 0790 0c41 0afd 092b 0a9d 082f 0cf8 0547 0295 00ec 0588 0733 0519 0795 02fd 0394 08d1 00e6 0444 064c 0969 00cb 066f 0936 01c0 09a9 0b87 099f 00c8 06aa 0172 0ba4 065a 048b 091a 08c4 00d6 0511 057e 0438 017a 0277 03bc 04f4 08d0 0a42 02a5 0bc8 0b6d 039a 0017 
A[0,2] = 02ba 0443 04d9 0c8f 04be 046b 09b5 0af6 09f0 0051 0a18 05ef 088e 06e8 0a98 0081 0cf6 02d6 02ae 09bf 02c8 0806 00b3 09bc 07ef 09dd 0196 0466 0b3e 0291 09a8 0277 0a91 069e 022b 0022 0539 06c5 006f 097c 0c46 0251 0ab1 0982 0546 0546 03e2 0351 09ca 0059 056d 0c3a 0799 0755 03e3 0ca5 0213 089d 0316 0604 0b13 0724 05ee 095f 01ae 04e9 07c6 069d 0594 09fa 03fb 070b 0848 0177 0551 02f9 05fb 0cd9 0b96 0404 07a3 01bf 03ee 0985 0829 0af7 06c2 02f6 04c8 0a74 01ac 039a 0a25 0cf4 02f5 06cf 0475 031b 0077 026e 04f3 0188 0846 0202 0b50 0789 0355 0a42 0054 0b7f 09c8 0785 0269 0419 019e 0aa6 0737 0c89 0acb 079c 0b9d 03bd 0305 003d 0a91 0a76 08bf 052f 00ea 05ac 0cbc 06dc 017f 051e 00be 08d0 0773 044d 0309 0446 039a 03c3 03be 0272 0346 06c8 03cf 0425 0bc0 01c8 02d0 0993 0ba0 002b 0ced 0b0a 0530 0226 0424 0548 0b97 034c 0bf9 06bd 0cc9 03ca 061d 0253 069a 0cc7 036f 0305 0a99 0c26 0477 0c9d 0916 045d 0ab1 098a 0027 00cf 02f0 0570 0984 06bc 0ce7 0444 0396 060e 0642 0271 07b7 052f 041e 0376 0123 0beb 0144 0825 05b9 0ca8 0b79 090c 0698 0771 0b1a 0956 0b1f 0121 0685 098f 0802 079c 0155 0b47 00ca 091f 0ab1 097c 006b 04ee 09e7 07f1 002b 0080 0776 0025 0549 0375 08cc 021b 02ea 0720 058f 0373 0ac0 060d 08fb 00a5 0125 0854 01af 0319 02f0 0313 05a0 06db 04d0 0494 0b67 08e0 09ce 0c7e 0254 0bfe 
A[1,0] = 057d 03e8 0760 0a29 0296 0422 08db 0a6d 0189 02ff 03da 00af 0385 07b5 04fe 0ac5 0493 00f2 0399 05ef 0bab 03e4 0ab0 002b 0567 0387 0831 0afe 070a 09d8 0b84 0cbb 00a4 0182 0ab9 0948 04da 0b53 022b 072c 0988 020c 0830 0b5f 0448 0ba6 002f 0456 01f1 0674 0b92 078e 087b 02b1 09a9 00b4 02ff 019d 02c3 08c5 0abd 0cd5 0c48 0709 03bc 0792 02b0 0bf5 01e8 0a4f 002f 05db 0709 0429 0316 0077 0515 070d 0c95 0466 04bb 0008 0baa 02ec 09b3 04cb 01a3 0c26 0785 03c8 0949 085f 0b09 0354 0833 0645 0a79 0387 0b6f 0575 0831 0bb7 02ff 0821 07fb 0407 0c67 04a9 07fd 03d1 04c6 00b1 087c 0bc5 0bc4 027c 02e4 095d 007c 03a9 0054 08be 0633 0c17 0a97 06d2 0738 0a09 03ba 09c0 008e 0b82 0673 0386 0001 0aee 091d 0433 0c15 03d7 0595 063b 01c6 041e 0a79 00a3 0110 0b06 03b7 0707 0cfc 0162 025b 0275 0cf4 0147 0660 0ade 08bb 0477 0a1e 0ca1 0016 0543 02e4 0449 0a53 05b7 0814 060c 04a4 00dc 0c3b 08c2 0784 0ae9 0b4c 0c4a 08f1 0b81 09cf 0ae3 021e 0cd7 028e 04a4 03f9 01ae 03b4 0638 09c5 0314 00c6 0b0b 0c2c 0bd2 0174 0c4b 07e8 0251 0b57 07db 0b88 0624 0b30 04cb 00d0 017f 0a68 0388 06e4 0c6b 02b2 0126 0be3 02ed 0125 017d 0ba9 024a 0be2 0a6b 07d7 092f 00b1 051f 0bca 001c 05b2 0c55 0548 01d2 064f 043b 025c 0331 09fa 04ca 0cfc 0afc 0a47 0b17 0b2d 049d 0872 07b3 0956 0b06 093d 0b6a 0618 09be 0632 0198 0cc3 05ae 
A[1,1] = 0011 071e 06f8 0aef 0475 0c89 090b 0423 0cf6 0649 0995 0ae4 046a 07dc 070f 01e8 0b52 08e1 0542 02bb 0cd5 071b 0889 05a8 0b09 064b 014a 01c6 0255 0752 0a09 07f2 06c1 0404 04f7 04dd 0afb 0cf3 0c98 09a1 06f3 024a 0b1b 02fb 0084 05d1 0b5f 001f 0784 02ee 09e8 0677 0213 00f9 0988 0879 035e 05c7 0cfa 011c 0332 03b0 06c9 0980 07ca 09df 01a7 0ab8 026d 0437 0693 0753 070b 021a 0849 04ad 0c0c 01af 03ba 0c3f 05e6 04d0 032b 0c58 02b6 0756 01ee 023c 0357 0803 083b 0115 0a2d 057c 011d 0003 05a1 01f5 03b1 063b 09e5 0c91 022e 0062 0979 089c 0adb 017e 03d0 03db 021d 0964 0316 04d7 0827 0bad 0b53 08a7 062c 05ea 067c 07aa 08ca 03b7 0370 0647 095c 0156 080e 0248 0797 0427 01c2 0276 06c5 046c 02f8 0cd7 03d4 0aa9 08b0 0412 085c 08e4 049e 0915 0876 08f2 0289 0b2c 01ce 0516 0454 0a54 01ea 0526 0532 0164 04ee 07bf 0b32 0a6f 095f 094e 01c1 07dc 0366 071b 07f3 09e5 08a9 0076 0a48 0209 0516 073f 0297 0380 00ef 097c 001b 093b 0cc7 065a 0230 0245 0a5e 0c04 0905 0443 0541 0a35 017a 0b6f 05cb 0459 0477 0b4a 0a5d 09e4 04d2 02a4 0064 09cf 0c5f 051b 062f 0c06 0c75 0758 05c6 0547 01ab 09b7 09ba 002d 07bc 058b 0aa0 0232 0595 0a39 05a1 0c23 03b7 0a45 0bb3 060f 03ef 047e 0371 0cb2 05e0 07c4 0aee 0345 0075 08b7 08ff 0279 0829 0915 0b83 0188 08b0 0a73 0b2f 00b4 0694 030a 0c85 0b50 05b0 03df 0277 080e 
A[1,2] = 0ba8 00d5 0730 0734 0b00 0534 04ba 02b2 0ac8 0539 075e 063a 03e6 095e 0cff 06a3 0cd1 0b00 0b9f 07df 08ab 01f9 0225 051d 0758 041e 0813 08e8 0479 08a0 02a7 060f 078c 0492 0a6c 02e7 08b6 0252 01f0 083b 0500 066f 0699 0b2c 0574 0047 0397 0a37 00f5 0362 004a 0883 06de 09ae 0c81 04c2 0699 05c7 0a51 0a55 02e0 0177 0309 02f4 051b 095c 0279 0058 01ae 0a34 04db 0bff 03a3 0a46 0730 0b0c 0a33 0682 02b2 08e6 0473 063d 0318 0165 0a83 02c4 0a00 0c32 0581 0ac1 015c 090f 0c3d 0adf 020b 0956 0286 028b 04c4 03e2 0a91 0bf2 00c0 0405 078e 0213 06fb 03a8 046f 0087 06d7 06a9 03ed 080f 0455 0059 0749 00f3 0105 042d 08b5 0436 0bfe 037a 0580 002f 08f2 0405 009a 0129 05f1 0be4 0ab9 0249 05c3 0676 0a0c 04a1 05e7 0173 08d8 04df 02bf 08cf 046d 06fe 038c 0331 06a1 04d3 02c5 00c2 0aa1 0bb6 04df 0292 0440 0992 02bc 0920 026d 02a2 0b13 0c2f 0973 0ac0 0943 0b56 04be 0931 0b1f 068f 0675 06fd 07ef 09a8 0a40 01e4 0a1d 058a 0743 04a5 074b 00bc 0a98 09b2 0b6f 09b7 0471 0379 0459 0c84 093f 0049 0928 005d 05e6 0b6c 070b 02e5 0c2b 0935 0465 01e6 055d 0b7f 0116 050b 0473 05af 03e5 06a0 0b02 0974 00e8 072c 0794 07cb 0496 0977 0372 0bb5 062d 090b 0af8 0b07 02d9 0a6b 0367 037c 07f8 0737 03e5 039e 0506 022c 0613 09a7 0aac 00b5 0ca0 0734 0b6e 0cde 07cf 0925 0217 01d4 019b 0179 089a 0504 059d 0cbf 0898 0b85 
A[2,0] = 095d 0244 026f 0c6f 06ee 0509 02b0 0537 0246 05c0 0736 0629 021b 0469 073f 0725 01c0 0078 04c9 0393 07c2 08dc 01c2 0854 0396 071d 04bb 0027 0842 05ff 02d7 04cf 0157 05c0 041c 0161 08b2 00ad 0c8e 0832 01d3 0655 0ce2 06fd 02a9 0a4a 0807 011d 06e5 0ae3 0361 0686 0ab9 0487 0381 0a15 0141 0a67 00d8 0680 02ef 05b1 0843 007f 075b 0659 0083 042c 06c1 004d 03b9 0afe 004f 0a3a 079e 07b6 021a 06f7 0047 0872 0147 01d6 0b24 0aa6 0475 0167 0984 0b49 0c94 09b9 0b2d 0943 0373 0cb2 032c 0452 08d3 0971 0aed 0451 07d1 0bb5 0a8e 0c79 0ae9 05dd 0adc 0121 0115 025f 0864 05ab 071e 0939 024f 02dc 0269 0156 0b04 06e4 0825 05bb 0523 0655 0462 02f2 0961 0972 08c9 0627 07c1 0c6f 01b1 01b3 0959 0a1b 0891 021d 07c0 0530 02f8 0955 0bb2 0081 0874 00d4 0bae 0c27 0c0c 08eb 041e 0300 006a 0c41 077a 0001 0bdc 0894 06e6 0b38 04b2 08e8 0084 038c 0ad8 0a04 0c02 048e 0325 0b92 07a8 0c3b 0723 0c91 0be6 0918 07e1 0845 01b5 0257 0c9f 0a75 03d3 009e 0b87 00f4 0aa4 0972 04eb 0b91 05f4 075c 0844 0368 0a48 0a41 0c6c 0991 0541 0ab9 093d 0911 00b3 04d7 05aa 0a7a 0a23 0cdd 070d 0715 085b 066a 072b 0a07 07d7 0c42 0671 058a 0c65 01e6 0593 01c7 0abd 0081 026b 0bcf 07e6 02dc 0291 0878 031b 09eb 07cd 02aa 0a3b 0ce7 02b3 0a9a 0684 0a1b 009d 0067 0b18 086f 0441 0219 0898 0bfb 04ce 0c60 0cc6 09a4 0432 0b20 0921 0a1b 
A[2,1] = 01ba 08a4 0363 046d 03eb 0392 09a0 0c5d 0298 0614 06bc 0813 057f 0694 05c4 09f8 0444 0b9a 0727 0bcd 0616 028d 0577 0c39 0548 08ec 0324 04ab 026e 0a62 0bf3 089e 09d3 02e2 0739 023c 09a9 08d2 0573 03cf 0ae9 0c1d 0021 028c 047e 0939 0cf9 0b63 08c2 0391 05db 08f6 06fb 06d8 0498 0afe 094b 0c0f 0698 0466 0759 0445 0082 0359 052e 02be 09b3 0322 04ee 0ae0 05ee 0b8d 094b 089f 0aae 08ff 02ad 05fa 0772 0036 087a 0571 0757 05a7 07c9 0ab3 01e4 0083 0c7e 0ca6 006a 0cc0 0cfb 0099 0c79 0538 016e 08ce 034f 0889 0c24 00cb 0c28 094f 09f7 0048 0584 0aea 0492 0b82 0973 0cf7 08ba 051d 031e 04fb 02f9 0468 03f0 01c2 04de 0ceb 0b08 05cd 08e3 0639 029a 03a5 0b34 0abc 0102 0bc7 0637 083b 0019 07b8 09fb 0025 028f 0343 04a8 07a2 06bc 05f8 04e7 0bd8 06a1 0b33 052e 09fd 0407 0a42 0586 0af8 0323 08bb 0b51 0b4b 05a5 0755 05dc 05f4 075c 0997 06b1 0c3b 083a 01a1 0970 0877 0089 092a 0385 0983 0634 07ec 0259 0af9 0809 0cd5 092f 0580 060b 08ad 0886 0599 08d0 0290 04e9 0aee 059d 0101 016d 0c16 0a8b 0cc5 0168 0152 07a9 06b9 03da 0169 0bd2 0680 0b71 02e0 0b9e 025c 0cec 0128 0b09 01a3 008c 06d4 0c12 0121 0064 0611 06b7 00ea 0257 0383 0d00 09b0 0b34 053e 086b 0966 0884 06ff 08d1 0a78 099b 004b 09fd 029d 0458 035f 09e3 0cca 032c 0360 0a93 0625 08d1 02d5 0334 07e4 0277 0769 0086 0020 03f3 05a7 08a2 0557 
A[2,2] = 07ce 0360 09ad 03de 0046 0c3f 05f3 0bd5 0947 0986 0cf9 0033 02c2 006d 019c 0418 0a4a 08da 06f5 0192 04e5 0948 0355 00e7 06fc 0b7f 051f 0aae 0c2c 07f1 0791 0b7f 0af1 0add 066a 0633 0496 037e 0059 0540 0a22 0052 03a2 01b2 0623 08f8 05a1 06b3 089d 0456 0b59 0614 0718 09db 04e6 0bc6 0a8b 02a2 07c6 0052 083c 08cb 0cd1 03ca 08c2 0cb3 0147 0196 0184 0a96 005a 0c7d 0305 03e8 0564 0cd0 0728 080c 0b83 0476 0288 0634 0cac 0621 084a 058f 02aa 0269 00c3 0075 09c4 00ed 0681 027d 0412 0358 01cd 0926 071b 06ee 078a 078e 03a5 04fb 0b8a 0c6c 0283 040f 089a 0b92 08ed 07cf 0ab1 0211 0b80 0889 0415 0184 026d 0ba3 0b28 03ad 06a8 0694 03e4 0cd8 0c33 053a 0747 0248 0afe 066e 0445 08fc 0147 0bcf 073f 00cc 01c8 0a2f 024d 04cf 0664 0743 02fc 048a 085e 05e4 01fa 080a 0744 0402 0a4e 0726 094f 05ba 0595 0c9c 05c6 06af 01b0 0906 044a 095b 0b84 0010 04ab 0451 00ce 03e4 010a 04a6 0aeb 0588 072e 0565 0284 0959 0517 09ad 0a2a 0795 0c7c 0a4a 0058 0562 00bb 037d 07d1 0c94 02a3 034d 0244 0c3f 04ad 0569 0260 04fc 02f6 0982 044b 040b 0388 0c08 04c9 00f8 0888 0cf7 0458 036f 0aec 0432 0379 07c1 0464 0c7b 0aa1 0418 0a30 007c 09d6 0340 09ec 0848 06b8 0670 0945 06e6 019b 03a9 0094 019e 04ab 06bd 043e 0391 088c 0677 0ce4 0b54 005b 0200 0b80 069e 0977 0230 0178 049b 01ff 08c6 01d3 02f2 00da 099e 018a 0811 

```

you seem to encode

**Comment by kriskwiatkowski** [comment]
Look, I think the problem is with rho and sigma calculation (and I think rest is OK). What I get is this

```
d=19EDABC9B0A65386CE5C2E7AEC648ED50D8EE84A6E6176D639AEC8A8C09F5152
rho=A38385F8CF4808493D63849B3FD441EABA886C318F61E8CFDC80460ED99753BE
sigma=379F82A8633069119760307DAF9EB6FBCDF02EA6F0607B0D8B0EC7418BB8ACF2
```

Algorithm 12 in step 2, computes ``(rho,sigma) = G(d)``. Where ``G`` is SHA3-512.

**Comment by rod-chapman** [comment]
Apologies - there's the output of 2 test cases in that file, and the first is a red herring. Here it is again with the first group of output removed. The second case corresponds to your "count = 0" case. Here, the rho and sigma values look OK I think.


[new_detail2.txt](https://github.com/post-quantum-cryptography/KAT/files/12902352/new_detail2.txt)

**Comment by rod-chapman** [comment]
I have a query about SamplePolyCBD() (Algorithm 7, lines 3 and 4). Is the summation over j = 0 .. (Eta - 1) supposed to be done using pure integer arithmetic, or modulo 2? That's not entirely clear in the spec. My code uses the former approach, so both x and y are in range 0 .. 2, so the returned values are members of (-2, -1, 0, 1, 2) mod 3329, or (0xcff, 0xd00, 0, 1, 2)

Does that look right to you?

**Comment by rod-chapman** [comment]
I did some checking:
At your commit 0513616 (basically, Thursday morning...) I got identical results to yours, but my code was using the "J, I" ordering for XOF() in _both_ KeyGen() and Encrypt().

Something has diverged since then. I changed both calls to use "I, J".

**Comment by kriskwiatkowski** [comment]
Thanks. Let me check again. 
The only change is the switch from J,I to I,J

**Comment by rod-chapman** [comment]
Do you agree with my implementation of SamplePolyCBD() above?

**Comment by kriskwiatkowski** [comment]
Oh, sorry, I've missed that comment. My interpretation is that this is pure integer arithmetic. Note that eta is very small (2 or 3).

**Comment by kriskwiatkowski** [comment]
Can you let me know if those samples work for you?

[sample10.82a57f13dd99c.txt](https://github.com/post-quantum-cryptography/KAT/files/12903085/sample10.82a57f13dd99c.txt)

**Comment by rod-chapman** [comment]
Yes! The first KAT matches perfectly now...

**Comment by kriskwiatkowski** [comment]
Great! Finally. Need to go somewhere,
I'll regenerate the KATs during the day.

**Comment by rod-chapman** [comment]
Same here... I will work on reproducing the whole file...

**Comment by kriskwiatkowski** [comment]
I've regenerated MLKEM vectors and pushed to the repo.

**Comment by rod-chapman** [comment]
Great news! I have managed to reproduce results byte-for-byte for the entire file, so I think we're in good shape.

**Comment by kriskwiatkowski** [comment]
Perfect. Thanks for all the effort Roderic.
